# Generated by Django 5.0.1 on 2024-01-05 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_question_min_score_alter_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_score', models.IntegerField()),
                ('pass_score', models.IntegerField()),
                ('predicted_score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='answer_published')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question')),
            ],
        ),
    ]
