# Generated by Django 5.0.1 on 2024-01-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_answer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='set_no',
            field=models.IntegerField(),
        ),
    ]
