# Generated by Django 5.0.1 on 2024-01-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question_prompt_alter_question_set_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prompt',
            new_name='source_essay',
        ),
    ]
