# Generated by Django 3.1 on 2020-08-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='set',
            new_name='set_no',
        ),
    ]
