# Generated by Django 3.1 on 2020-08-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200827_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essay',
        ),
    ]
