# Generated by Django 5.0.1 on 2024-01-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200827_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='min_score',
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
